# Generated by Django 4.2.16 on 2026-06-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_alter_plan_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duracion_dias',
            field=models.IntegerField(default=30),
        ),
    ]
