# Generated by Django 5.1.4 on 2025-01-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_suscripcion_acepto_terminos_venta_acepto_terminos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosYCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True, help_text='Ej: v1.0, 2024-01')),
                ('contenido', models.TextField(help_text='Contenido HTML o texto plano de los términos')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se mostrará a los usuarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
            },
        ),
    ]
