# Generated by Django 5.1.4 on 2025-01-18 20:54

from django.db import migrations


def insert_terminos_y_condiciones(apps, schema_editor):
    TerminosYCondiciones = apps.get_model('usuarios', 'TerminosYCondiciones')
    
    # Verificar si ya existe algún término
    if not TerminosYCondiciones.objects.filter(activo=True).exists():
        TerminosYCondiciones.objects.create(
            version='1.0',
            contenido="""<h1 style="text-align: center;"><strong>TÉRMINOS Y CONDICIONES - GYMXTREME</strong></h1>
<p style="text-align: left;"><strong>1. RESPONSABILIDAD DEL CLIENTE:</strong><br>El cliente declara que se encuentra en condiciones físicas aptas para realizar actividad física y es responsable de elegir el plan adecuado según su estado de salud.</p>
<p style="text-align: left;"><strong>2. EXONERACIÓN DE RESPONSABILIDAD:</strong><br>GymXtreme no se hace responsable por lesiones, accidentes o cualquier problema de salud que pueda surgir dentro de las instalaciones o durante la ejecución de rutinas.</p>
<p style="text-align: left;"><strong>3. VALORACIÓN MÉDICA:</strong><br>Se recomienda al cliente consultar con un médico antes de iniciar cualquier programa de entrenamiento.</p>
<p style="text-align: left;"><strong>4. USO DE INSTALACIONES:</strong><br>El uso de máquinas, equipos y áreas del gimnasio es bajo responsabilidad del cliente.</p>
<p style="text-align: left;"><strong>5. PAGOS Y DEVOLUCIONES:</strong><br>No se realizan devoluciones una vez efectuado el pago del plan adquirido.</p>
<p style="text-align: left;"><strong>6. NORMAS INTERNAS:</strong><br>El cliente se compromete a cumplir con todas las normas internas del gimnasio.</p>
<p style="text-align: left;"><strong>7. ACEPTACIÓN:</strong><br>Al continuar con la compra, el cliente acepta estos términos y condiciones en su totalidad.</p>""",
            activo=True
        )


def reverse_insert_terminos_y_condiciones(apps, schema_editor):
    TerminosYCondiciones = apps.get_model('usuarios', 'TerminosYCondiciones')
    TerminosYCondiciones.objects.filter(version='1.0').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_terminosycondiciones'),
    ]

    operations = [
        migrations.RunPython(insert_terminos_y_condiciones, reverse_insert_terminos_y_condiciones),
    ]
