# Generated by Django 4.2.16 on 2026-06-03 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_add_subscription_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
