# Generated by Django 4.2.16 on 2026-04-19 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0004_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('origen', models.CharField(blank=True, choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20, null=True)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID de la compra, venta u otro movimiento', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_inventario', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Inventario',
                'verbose_name_plural': 'Historial de Inventario',
                'db_table': 'historial_inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
