# Generated by Django 4.2.16 on 2026-04-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_historialinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(editable=False, help_text='Generado automáticamente (ej: LOTE001)', max_length=50)),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad de unidades en este lote')),
                ('fecha_fabricacion', models.DateField(help_text='Fecha de fabricación del producto')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del lote')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido')], default='disponible', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('producto', 'numero_lote')},
            },
        ),
    ]
