# Generated by Django 4.2.16 on 2026-04-27 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Fecha de compra del lote', null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario de compra de este lote', max_digits=10),
        ),
        migrations.CreateModel(
            name='AlertaLote',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', help_text='Nivel de severidad de la alerta', max_length=10)),
                ('dias_para_vencer', models.IntegerField(help_text='Días restantes cuando se generó la alerta')),
                ('titulo', models.CharField(help_text='Título de la alerta', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la alerta', null=True)),
                ('leida', models.BooleanField(default=False, help_text='Si la alerta ha sido leída')),
                ('activa', models.BooleanField(default=True, help_text='Si la alerta sigue siendo relevante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='productos.lote')),
            ],
            options={
                'verbose_name': 'Alerta de Lote',
                'verbose_name_plural': 'Alertas de Lotes',
                'db_table': 'alertas_lotes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
