# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_lote_fecha_compra_lote_precio_unitario_alertalote'),
    ]

    operations = [
        # Add es_consumible field to Categoria
        migrations.AddField(
            model_name='categoria',
            name='es_consumible',
            field=models.BooleanField(
                default=False,
                help_text='Marcar si los productos de esta categoria son consumibles (suplementos) o no (ropa/accesorios). Los consumibles manejan lotes con fechas de fabricacion y vencimiento.'
            ),
        ),
        # Add numero_lote_fabricante to Lote
        migrations.AddField(
            model_name='lote',
            name='numero_lote_fabricante',
            field=models.CharField(
                blank=True,
                help_text='Numero de lote proporcionado por el fabricante (opcional, para consumibles)',
                max_length=100,
                null=True,
            ),
        ),
        # Make fecha_fabricacion nullable
        migrations.AlterField(
            model_name='lote',
            name='fecha_fabricacion',
            field=models.DateField(
                blank=True,
                help_text='Fecha de fabricacion del producto (solo para consumibles)',
                null=True,
            ),
        ),
        # Make fecha_vencimiento nullable
        migrations.AlterField(
            model_name='lote',
            name='fecha_vencimiento',
            field=models.DateField(
                blank=True,
                help_text='Fecha de vencimiento del lote (solo para consumibles)',
                null=True,
            ),
        ),
    ]