# Generated by Django 4.2.16 on 2026-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_categoria_consumible_lote_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(editable=False, help_text='Generado automaticamente (ej: LOTE001)', max_length=50),
        ),
    ]
