# Generated by Django 4.2.16 on 2026-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, help_text='Fecha de fabricación del producto (solo para consumibles)', null=True),
        ),
    ]
